<?php

namespace AppBundle\Repository;

/**
 * PitcuresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PitcuresRepository extends \Doctrine\ORM\EntityRepository
{
}
